config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  devise_for :users, only: %i[sessions registrations passwords], path: '', path_names: {
    sign_in: 'session/login',
    registration: 'session/simple-register',
    sign_up: ''
  }

  resources :movies, only: %i[index search movies_catalog show] do
    get :search, on: :collection
  end

  get 'movies/search/:q', to: 'movies#search', as: 'movies_search_name'

  resources :favorites, only: %i[index create destroy]
  resources :rents, only: %i[create destroy]

  get   'media/movies/:id/:title',    to: 'movies#show',            as: 'media_movie'
  get   'catalog/:id/:catalog_name',  to: 'movies#movies_catalog',  as: 'movie_catalog'

  get   'accounts/register',          to: 'adresses#new',           as: 'new_adress'
  patch 'accounts/register',          to: 'adresses#edit',          as: 'edit_adress'
  post  'accounts/register',          to: 'adresses#create'

  # Não definitivas

  get   'accounts/change_password',   to: 'users#edit'

  patch 'profile_name',               to: 'users#update_name'
  patch 'profile_password',           to: 'users#update_password'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include OptionsCategories

  before_action :set_movie, only: :show
  before_action :set_movie_category
  before_action :set_movie_popular

  def index
    @movies = Movie.all

    @first_movie = Movie.where.not(slide: nil)
  end

  def search
    @movies = Movie.search(search_params[:q]).where.not("card_image ILIKE '%/ban/%'")
  end

  def movies_catalog; end

  def show; end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def search_params
    params.permit(:q)
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def search_movie_by_category(category)
    movies = Category.find(category).movies

    movies.where.not('card_image ILIKE ?', '%/ban/%').order(title: :desc, description: :desc).first(15)
  end
end

app/views/movies/_nav_options.html.erb
<div class="nav-options">
  <% if user_signed_in? %>
    <div class="content-options desable-options-desk">
      <ul class="menu-user">
        <li class="hover-list">
          <%= link_to accounts_register_path do %>
            <%= image_tag(current_user.avatar_thumbnail, alt: "user", class: "user_avatar") %>
            <span>Minha Conta</span>
          <% end %>
        </li>
        <li class="hover-list">
          <%= link_to favorites_path do %>
            <%= image_tag('like.svg', alt: "heart") %>
            <span>Favoritos</span>
          <% end %>
        </li>
        <li class="hover-list">
          <%= link_to destroy_user_session_path do %>
            <%= image_tag('logout.svg', alt: "logout") %>
            <span>Sair</span>
          <% end %>
        </li>
      </ul>
    </div>
  <% end %>
  <div class="content-options">
    <h2>Gênero</h2>
    <ul class="menu-options">
      <% @categories.each do |category| %>
        <li class="hover-list">
          <%= link_to movie_catalog_path(category.id, category.category) do %>
            <span><%= category.category_by(category.category) %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="content-options">
    <h2>Populares</h2>
    <ul class="menu-options">
      <% @popularity.each do |p| %>
        <li class="hover-list">
          <%= link_to movie_catalog_path(p.id, p.category_by(p.category)) do %>
            <span><%= p.category_by(p.category) %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="nav-options-mobile">
  <div class="content-options">
    <div class="nav-exit"></div>

    <h2>Gêneros</h2>
    <ul class="menu-options">
      <% @categories.each do |category| %>
        <li class="hover-list">
          <%= link_to movie_catalog_path(category.id, category.category) do %>
            <span><%= category.category %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="nav-search-mobile">
  <div class="nav-exit"></div>

  <div class="search-mobile">
    <%= form_with url: search_movies_path, method: :get, local: true, class: 'search-form-mobile' do |f| %>
      <%= f.text_field :q, class: "input", required: true, placeholder: "Filmes, séries, shows..." %>
      <%= f.button "Buscar", type: "submit" %>
    <% end %>
    <div class="btn-mobile">
      <%= image_tag('search.svg', alt: 'search', class: 'magnifying-glass') %>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<section class="swiper mySwiperCarousel">
  <div class="swiper-wrapper">
    <% @first_movie.each do |movie| %>
      <%= link_to media_movie_path(movie.id, movie.title), class: "swiper-slide" do %>
        <%= image_tag(movie.slide, alt: movie.title) %>
      <% end %>
    <% end %>
  </div>
  <div class="swiper-pagination"></div>
</section>

<% @categories.each do |category| %>
  <section class="swiper-cards">
    <div class="swiper mySwiperCard">
      <%= link_to movie_catalog_path(category.id, category.category) do %>
        <header>
          <h2><%= category.category %></h2>
        </header>
      <% end %>
      <div class="swiper-wrapper">
        <% search_movie_by_category(category.id).each do |movie| %>
          <div class="swiper-slide slide-card">
            <%= link_to media_movie_path(movie.id, movie.title) do %>
              <%= image_tag(movie.card_image.to_str, alt: movie.title) %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="swiper-button-next"></div>
      <div class="swiper-button-prev"></div>
    </div>
  </section>
<% end %>

app/views/movies/movies_catalog.html.erb
<main class="main-movies">
  <header>
    <h1><%= params[:catalog_name] %></h1>
  </header>

  <div>
    <ul>
      <% search_movie_by_category(params[:id]).each do |movie| %>
        <li>
          <div>
            <%= link_to media_movie_path(movie.id, movie.title) do %>
              <%= image_tag(movie.card_image) %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</main>

app/views/movies/search.html.erb
<main class="main-movies">
  <header class="header-search-movie">
    <h1>
      <%= @movies.empty? ? 'Nenhum resultado encontrado (╥_╥)' :
        "Busca por '#{params[:q]}': #{pluralize(@movies.count, "resultado encontrado")}"
      %>
    </h1>
  </header>

  <div>
    <ul>
      <% @movies.each do |movie| %>
        <li>
          <div>
            <%= link_to media_movie_path(movie.id, movie.title) do %>
              <%= image_tag(movie.card_image) %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</main>

app/views/movies/show.html.erb
<main class="main-movie-details">
  <div class="main-movie-details-content">
    <div class="video-play-container">
      <div class="movie-config mobile-video-play">
        <video loop muted class="video">
          <source src="<%= @movie.background_video %>" type="video/mp4">
        </video>

        <%# <div class="play">
          <div></div>
        </div> %>
        
        <%= image_tag(@movie.background_image, class: "movie-image movie-image-mobile", alt: @movie.title)%>
      </div>
    </div>

    <div class="button-video-play">
      <button type="button" class="play-start-movie">
        <%= image_tag('play.svg', alt: 'play') %>
      </button>
      
      <button type="button" class="button-audio">
        <%= image_tag('volume.svg', alt: 'volume') %>
      </button>

      <button type="button" class="display-details">
        <%= image_tag('display.svg', alt: 'display') %>
      </button>
    </div>

    <div class="movie-infos">
      <div class="content-infos">
        <div class="details-header">
          <h1><%= @movie.title %></h1>
          <p>(<%= @movie.title_producer %>)</p>
        </div>
        
        <div class="details video-details-duration">
          <p>2010</p>
          <p>Estados Unidos</p>
          <p>88 minutos</p>
        </div>

        <%# <div class="validation-movie">
          <span>x</span>
          <span>x</span>
          <span>x</span>
          <span>x</span>
          <span>x</span>
        </div> %>
        <% unless user_signed_in? %>
          <div class="favorite-movie">
            <button type="button" class="like">
              <%= link_to new_user_session_path do %>
                <%= image_tag 'like.svg', alt: 'like' %>
              <% end %>
            </button>
            <span>(Adicionar aos favoritos)</span>
          </div>
        <% else %>
          <div
            class="favorite-movie"
            data-movie-id="<%= @movie.id %>"
            data-favorite-id="<%= @movie.favorites.find_by(user_id: current_user.id)&.id %>"
          >
            <button type="button" class="like <%= @movie.liked_by?(current_user.id) ? 'hidden' : '' %>">
              <%= image_tag 'like.svg', alt: 'like' %>
            </button>

            <button type="button" class="deslike <%= @movie.liked_by?(current_user.id) ? '' : 'hidden' %>">
              <%= image_tag 'liked.svg', alt: 'liked' %>
            </button>
            <span>(Adicionar aos favoritos)</span>
          </div>
        <% end %>
        <div class="category-movie">
          <% @movie.categories.each do |category| %>
            <span><%= category.category %>,</span>
          <% end %>
        </div>

        <div class="movie-language">
          <p>Dublado | HD</p>
          <p>Português</p>
        </div>

        <div class="description-movie">
          <p><%= @movie.description %></p>
        </div>

        <div class="actors-movie">
          <h3>Atores</h3>
          <ul>
            <% @movie.actors.each do |actor| %>
              <li>
                <%= link_to movies_search_name_path(actor.name) do %>
                  <%= actor.name %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="directors-movie">
          <h3>Diretores</h3>
          <ul>
            <% @movie.directors.each do |director| %>
              <li>
                <%= link_to movies_search_name_path(director.name) do %>
                  <%= director.name %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>

        <% unless user_signed_in? %>
          <div class="button-add-movie">
            <div>
              <%= link_to new_user_session_path do %> 
                <button type="button" class="to-hire">ALUGAR AGORA</button>
              <% end %>
            </div>
          </div>
        <% else %>
          <div
            class="button-add-movie"
            data-rent-movie-id="<%= @movie.id %>"
            data-rent-id="<%= @movie.rents.find_by(user_id: current_user.id)&.id %>"
          >
            <div>
              <button type="button" class="to-hire" <%= 'disabled' if current_user.rents.count == 3 %>>
                <% if @movie.rent_by?(current_user.id) %>
                  Entregar em 3 dias
                  <span class="date-time-rent">
                    (<%= time_ago_in_words(@movie.rent_by_date?(current_user.id, @movie.id)) %>)
                  </span>
                <% else %>
                  <%= current_user.rents.count < 3 ? 'ALUGAR AGORA' : 'Limite de aluguéis foi alcançado' %>
                <% end %>
              </button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</main>

<section class="swiper-cards">
  <div class="swiper mySwiperCard">
    <a>
      <header>
        <h2>Você também pode gostar</h2>
      </header>
    </a>
    <div class="swiper-wrapper">
      <% search_movie_by_category(@movie.categories[0].id).each do |movie| %>
        <div class="swiper-slide slide-card">
          <%= link_to media_movie_path(movie.id, movie.title) do %>
            <%= image_tag(movie.card_image, alt: movie.title) %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>
</section>