config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  devise_for :users, only: %i[sessions registrations passwords], path: '', path_names: {
    sign_in: 'session/login',
    registration: 'session/simple-register',
    sign_up: ''
  }

  resources :movies, only: %i[index search movies_catalog show] do
    get :search, on: :collection
  end

  get 'movies/search/:q', to: 'movies#search', as: 'movies_search_name'

  resources :favorites, only: %i[index create destroy]
  resources :rents, only: %i[create destroy]

  get   'media/movies/:id/:title',    to: 'movies#show',            as: 'media_movie'
  get   'catalog/:id/:catalog_name',  to: 'movies#movies_catalog',  as: 'movie_catalog'

  get   'accounts/register',          to: 'adresses#new',           as: 'new_adress'
  patch 'accounts/register',          to: 'adresses#edit',          as: 'edit_adress'
  post  'accounts/register',          to: 'adresses#create'

  # Não definitivas

  get   'accounts/change_password',   to: 'users#edit'

  patch 'profile_name',               to: 'users#update_name'
  patch 'profile_password',           to: 'users#update_password'
end

app/models/user.rb
class User < ApplicationRecord
  devise           :database_authenticatable,
                   :registerable,
                   :recoverable,
                   :rememberable,
                   :validatable

  validates        :name,   presence: true
  validates        :avatar, content_type: %i[png jpg jpeg]

  has_one_attached :avatar

  has_many         :favorites

  has_one          :address

  has_many :rents
  has_many :movies, through: :rents

  def avatar_thumbnail
    if avatar.attached?
      avatar.variant(resize: '50x50^', extent: '50x50')
    else
      'user.svg'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include OptionsCategories

  before_action :set_movie_category
  before_action :set_movie_popular

  def edit; end

  def update
    if current_user.update(users_params)
      redirect_to accounts_register_path, notice: "#{users_params.keys[0]} foi atualizado com sucesso."
    else
      flash.now[:alert] = current_user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def update_name
    update
  end

  def update_password
    update
  end

  private

  def users_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_nav_user.html.erb
<nav class="nav-user">
  <ul class="menu-user">
    <li class="hover-list">
      <%= link_to accounts_register_path do %>
        <% if user_signed_in? %>
          <%= image_tag(current_user.avatar_thumbnail, alt: "user", class: "user_avatar") %>
        <% end %>
        <span>Minha Conta</span>
      <% end %>
    </li>
    <li class="hover-list">
      <%= link_to favorites_path do %>
        <%= image_tag('like.svg', alt: "heart") %>
        <span>Favoritos</span>
      <% end %>
    </li>
    <li class="hover-list">
      <%= link_to destroy_user_session_path do %>
        <%= image_tag('logout.svg', alt: "logout") %>
        <span>Sair</span>
      <% end %>
    </li>
  </ul>
</nav>

app/views/users/edit.html.erb
<main class="main-user">
  <header class="user-header">
    <h1 class="df df_alc fw_bigue">Minha conta</h1>
  </header>
  <div class="content-form-user df">
    <%= render 'aside/nav_content' %>
    
    <div class="content-form">
      <section class="section-registration">
        <header>
          <h2 class="form-title">Alterar senha</h2>
        </header>

        <%= form_with model: current_user, url: profile_password_path, local: true, class: 'form-name-user' do |f| %>
          <div class="input-name-form-user w-input df df_fdc">
            <%= f.label :current_password %>
            <%= f.password_field :current_password,
              autocomplete: "current-password",
              placeholder: "Insira a sua senha atual",
              id: 'current_password'
            %>
          </div>

          <div class="input-name-form-user w-input df df_fdc">
            <%= f.label :password %>
            <%= f.password_field :password,
              autocomplete: "new-password",
              placeholder: "Insira uma nova senha",
              id: "new_password"
            %>
          </div>

          <div class="input-name-form-user w-input df df_fdc">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation,
              autocomplete: "new-password",
              placeholder: "Confirme a sua nova senha",
              id: "confirm_password"
            %>
          </div>

          <div class="button-edit-user button-edit-password w-input">
            <%= f.button "Alterar cadastro", type: "submit", class: "fw_light" %>
          </div>
        <% end %>
      </section>
    </div>
  </div>
</main>