config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  devise_for :users, only: %i[sessions registrations passwords], path: '', path_names: {
    sign_in: 'session/login',
    registration: 'session/simple-register',
    sign_up: ''
  }

  resources :movies, only: %i[index search movies_catalog show] do
    get :search, on: :collection
  end

  get 'movies/search/:q', to: 'movies#search', as: 'movies_search_name'

  resources :favorites, only: %i[index create destroy]
  resources :rents, only: %i[create destroy]

  get   'media/movies/:id/:title',    to: 'movies#show',            as: 'media_movie'
  get   'catalog/:id/:catalog_name',  to: 'movies#movies_catalog',  as: 'movie_catalog'

  get   'accounts/register',          to: 'adresses#new',           as: 'new_adress'
  patch 'accounts/register',          to: 'adresses#edit',          as: 'edit_adress'
  post  'accounts/register',          to: 'adresses#create'

  # Não definitivas

  get   'accounts/change_password',   to: 'users#edit'

  patch 'profile_name',               to: 'users#update_name'
  patch 'profile_password',           to: 'users#update_password'
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :movie_actors
  has_many :movies, through: :movie_actors
end

app/models/address.rb
class Address < ApplicationRecord
  validates   :number, uniqueness: true
  validates   :number,
              :zip_code,
              :city,
              :state,
              :street, presence: { message: 'deve estar presente' }

  belongs_to  :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :movie_categories
  has_many :movies, through: :movie_categories

  def category_by(category)
    case category
    when 'Western' then 'Filmes de Bang Bang!'
    when 'Infantil' then 'EU TÔ DE FÉRIAS!'
    else
      category
    end
  end
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movie_directors
  has_many :movies, through: :movie_directors
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates  :movie_id, uniqueness: { scope: :user_id, message: 'Esse filme já está em favoritado' }
end

app/models/movie.rb
class Movie < ApplicationRecord
  include PgSearch::Model

  validates :title,
            :title_producer,
            :release_year,
            :background_image,
            :background_video,
            :card_image,
            :description, presence: true
  validates :release_year, numericality: true
  validates :description, length: { minimum: 50 }

  has_many :movie_categories
  has_many :categories, through: :movie_categories

  has_many :movie_actors
  has_many :actors, through: :movie_actors

  has_many :movie_directors
  has_many :directors, through: :movie_directors

  has_many :rents
  has_many :users, through: :rents

  has_many :favorites, dependent: :destroy

  pg_search_scope :search, against: :title, associated_against: {
    actors: :name,
    directors: :name
  }

  def liked_by?(user)
    favorites.where(user_id: user).exists?
  end

  def rent_by?(user)
    rents.where(user_id: user).exists?
  end

  def rent_by_date?(user, movie)
    rents.where(movie_id: movie, user_id: user)[0][:created_at]
  end
end

app/models/movie_actor.rb
class MovieActor < ApplicationRecord
  belongs_to :actor, optional: true
  belongs_to :movie, optional: true
end

app/models/movie_category.rb
class MovieCategory < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :movie, optional: true
end

app/models/movie_director.rb
class MovieDirector < ApplicationRecord
  belongs_to :director, optional: true
  belongs_to :movie, optional: true
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :movie
  belongs_to :user

  validates  :movie_id, uniqueness: { scope: :user_id, message: 'Este filme já foi alugado' }
end

app/models/user.rb
class User < ApplicationRecord
  devise           :database_authenticatable,
                   :registerable,
                   :recoverable,
                   :rememberable,
                   :validatable

  validates        :name,   presence: true
  validates        :avatar, content_type: %i[png jpg jpeg]

  has_one_attached :avatar

  has_many         :favorites

  has_one          :address

  has_many :rents
  has_many :movies, through: :rents

  def avatar_thumbnail
    if avatar.attached?
      avatar.variant(resize: '50x50^', extent: '50x50')
    else
      'user.svg'
    end
  end
end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController
  include OptionsCategories

  before_action :set_movie_category
  before_action :set_movie_popular

  def new
    @address = Address.new
  end

  def create
    if current_user.address.nil?
      create_address
    else
      edit
    end
  end

  def edit
    @address = Address.find(current_user.address.id)
    if @address.update(address_params)
      redirect_to new_adress_path, notice: 'Endereço atualizado com sucesso.'
    else
      flash.now[:alert] = @address.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def create_address
    @address = Address.new(address_params.merge(user: current_user))

    if @address.save
      render :new, notice: 'Endereço criado com sucesso.'
    else
      flash.now[:alert] = @address.errors.full_messages.to_sentence
      render :new
    end
  end

  def address_params
    params.require(:address).permit(:zip_code, :city, :state, :street, :number, :complement)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include OptionsCategories

  before_action :set_movie, only: :show
  before_action :set_movie_category
  before_action :set_movie_popular

  def index
    @movies = Movie.all

    @first_movie = Movie.where.not(slide: nil)
  end

  def search
    @movies = Movie.search(search_params[:q]).where.not("card_image ILIKE '%/ban/%'")
  end

  def movies_catalog; end

  def show; end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def search_params
    params.permit(:q)
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rents, only: :destroy

  def create
    like = Rent.new(user_id: current_user.id, movie_id: rent_params[:movie_id])

    if current_user.rents.count >= 3
      render json: { successful: false }
    elsif like.save
      render json: { successful: true }
    else
      render json: { successful: false }
    end
  end

  def destroy
    render json: { successful: @rent.destroy }
  end

  private

  def set_rents
    @rent = current_user.rents.find(params[:id])
  end

  def rent_params
    params.require(:rent).permit(:movie_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include OptionsCategories

  before_action :set_movie_category
  before_action :set_movie_popular

  def edit; end

  def update
    if current_user.update(users_params)
      redirect_to accounts_register_path, notice: "#{users_params.keys[0]} foi atualizado com sucesso."
    else
      flash.now[:alert] = current_user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def update_name
    update
  end

  def update_password
    update
  end

  private

  def users_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/adresses_helper.rb
module AdressesHelper
  def adress_exists?(value)
    current_user.address[value] unless current_user.address.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def search_movie_by_category(category)
    movies = Category.find(category).movies

    movies.where.not('card_image ILIKE ?', '%/ban/%').order(title: :desc, description: :desc).first(15)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aside/_nav_content.html.erb
<aside>
  <nav class="sidebar fw_light df df_fdc">
    <%= link_to "Cadastro", accounts_register_path, class: "hover-list" %>
    <%= link_to "Alterar Senha", accounts_change_password_path, class: "hover-list" %>
    <%= link_to "Favoritos", favorites_path, class: "hover-list" %>
  </nav>
</aside>

app/views/layouts/_footer.html.erb
<footer>
  <div class="content-footer">
    <h2>Contatos</h2>
    <div>
      <%= link_to image_tag('github.svg', alt: 'github'), 'https://github.com/FelipeNevess', target: '_blank' %>
      <%= link_to image_tag('whatsapp.svg', alt: 'whatsapp'), 'https://www.linkedin.com/in/felipe-nevess/', target: '_blank' %>
      <%= link_to image_tag('linkedin.svg', alt: 'linkedin'), 'https://www.linkedin.com/in/felipe-nevess/', target: '_blank' %>
    </div>

    <span>Copyright &#169 <%= Date.current.year %></span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="leyout-header">
  <div class="nav">
    <div class="menu <% unless user_signed_in? %>desable-menu<% end %>">
      <button type="button">
        <%= image_tag('menu.svg',  alt: "menu") %>
      </button>
    </div>
    <div class="logo">
      <%= link_to root_path do %>
        <h1>LOGO</h1>
      <% end %>
    </div>
  </div>
  <div class="nav">
    <div class="search">
      <%= form_with url: search_movies_path, method: :get, local: true, class: 'search-form' do |f| %>
        <%= f.text_field :q, class: "input", required: true, id: "search", placeholder: "Filmes, séries, shows..." %>
      <% end %>
      <button type="button" class="btn-search">
        <%= image_tag('search.svg', alt: "search") %>
      </button>
    </div>
    <% if user_signed_in? %>
      <div class="user-avatar">
        <button type="button" class="button-nav-user">
          <%= image_tag(current_user.avatar_thumbnail, alt: "user", class: "user_avatar") %>
        </button>
      </div>
    <% else %>
      <nav class="login">
        <ul>
          <li>
            <%= link_to 'Login', user_session_path %>
          </li>
          <li>
            <%= link_to 'Cadastrar', new_user_registration_path %>
          </li>
        </ul>
      </nav>
    <% end %>
  </div>
</header>

<%= render 'users/nav_user' %>
<%= render 'movies/nav_options' %>
  

app/views/layouts/_nav_header_mobile.html.erb
<ul class="nav-mobile">
  <li>
    <div>
      <%= link_to root_path do %>
        <%= image_tag("home.svg", alt: "home") %>
        <span>Home</span>
      <% end %>
    </div>
  </li>
  <li>
    <div>
      <button>
        <%= image_tag("search.svg", alt: "search", class: "search-button") %>
        <span>Busca</span>
      </button>
    </div>
  </li>
  <li>
    <div>
      <button>
        <%= image_tag("list.svg", alt: "list", class: "genre-list") %>
        <span>Generos</span>
      </button>
    </div>
  </li>
  <% if user_signed_in? %>
    <li>
      <div>
        <%= link_to favorites_path do %>
          <%= image_tag("like.svg", alt: "heart") %>
          <span>Favoritos</span>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>Locadora</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css"/>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-flash-messages="<%= JSON.dump(flash.to_a) %>">
    <%= render "layouts/header" %>

    <main>
      <%= yield %>

      <%= render "layouts/nav_header_mobile" %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>Locadora</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-flash-messages="<%= JSON.dump(flash.to_a) %>">
    <main class="login-main">
      <div class="container-login">
        <%= yield %>
      </div>
    </main>
  </body>
</html>