config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  devise_for :users, only: %i[sessions registrations passwords], path: '', path_names: {
    sign_in: 'session/login',
    registration: 'session/simple-register',
    sign_up: ''
  }

  resources :movies, only: %i[index search movies_catalog show] do
    get :search, on: :collection
  end

  get 'movies/search/:q', to: 'movies#search', as: 'movies_search_name'

  resources :favorites, only: %i[index create destroy]
  resources :rents, only: %i[create destroy]

  get   'media/movies/:id/:title',    to: 'movies#show',            as: 'media_movie'
  get   'catalog/:id/:catalog_name',  to: 'movies#movies_catalog',  as: 'movie_catalog'

  get   'accounts/register',          to: 'adresses#new',           as: 'new_adress'
  patch 'accounts/register',          to: 'adresses#edit',          as: 'edit_adress'
  post  'accounts/register',          to: 'adresses#create'

  # Não definitivas

  get   'accounts/change_password',   to: 'users#edit'

  patch 'profile_name',               to: 'users#update_name'
  patch 'profile_password',           to: 'users#update_password'
end

app/controllers/adresses_controller.rb
class AdressesController < ApplicationController
  include OptionsCategories

  before_action :set_movie_category
  before_action :set_movie_popular

  def new
    @address = Address.new
  end

  def create
    if current_user.address.nil?
      create_address
    else
      edit
    end
  end

  def edit
    @address = Address.find(current_user.address.id)
    if @address.update(address_params)
      redirect_to new_adress_path, notice: 'Endereço atualizado com sucesso.'
    else
      flash.now[:alert] = @address.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def create_address
    @address = Address.new(address_params.merge(user: current_user))

    if @address.save
      render :new, notice: 'Endereço criado com sucesso.'
    else
      flash.now[:alert] = @address.errors.full_messages.to_sentence
      render :new
    end
  end

  def address_params
    params.require(:address).permit(:zip_code, :city, :state, :street, :number, :complement)
  end
end

app/helpers/adresses_helper.rb
module AdressesHelper
  def adress_exists?(value)
    current_user.address[value] unless current_user.address.nil?
  end
end

app/views/adresses/new.html.erb
<main class="main-user">
  <header class="user-header">
    <h1 class="df df_alc fw_bigue">Minha conta</h1>
  </header>
  <div class="content-form-user df">
    
    <%= render 'aside/nav_content' %>

    <div class="content-form">
      <section class="section-registration">
        <header>
          <h2 class="form-title">Dados de cadastro</h2>
        </header>
        <p>Email: <span><%= current_user.email %></span></p>

        <%= form_with model: current_user, url: profile_name_path, local: true, class: 'form-name-user' do |f| %>
          <div class="input-name-form-user w-input df df_fdc">
            <%= f.label :name %>
            <%= f.text_field :name,
              value: current_user.name,
              autocomplete: "new-password",
              placeholder: "Informe o seu nome",
              disabled: true,
              id: :name
            %>

          </div>
          <div class="button-registration-user">
            <%= f.button "Alterar cadastro", type: "submit", class: "fw_light" %>
          </div>
        <% end %>
        <input type="button" value="Editar" id="habilit-input-edit">
      </section>

      <section class="section-address">
        <header>
          <h2 class="form-title">Dados de endereço</h2>
        </header>
        <%= form_with model: @address, url: accounts_register_path, local: true, class: "form-address-user" do |f| %>
          <div class="df df_fdc cep input-name-form-user">
            <%= f.label "CEP*:", for: "information-cep" %>
            <div>
              <%= f.text_field :zip_code,
                placeholder: "Insira o seu CEP",
                id: "information-cep",
                maxlength: 8,
                class: "disable",
                disabled: true,
                value: adress_exists?(:zip_code)
              %>
              <button type="button" class="buttons-desable search-cep">Buscar</button>
            </div>
          </div>

          <div class="df w-input">
            <div class="df df_fdc input-address-c1 w-input input-name-form-user">
              <%= f.label "Cidade", for: "information-city" %>

              <%= f.text_field :city,
                placeholder: "Cidade",
                id: "information-city",
                class: "disable",
                disabled: true,
                value: adress_exists?(:city)
              %>
            </div>

            <div class="df df_fdc input-address-c2 w-input input-name-form-user">
              <%= f.label "Estado", for: "information-state" %>

              <%= f.text_field :state,
                placeholder: "Estado",
                id: "information-state",
                class: "disable",
                disabled: true,
                value: adress_exists?(:state)
              %>
            </div>
          </div>

          <div class="df w-input">
            <div class="df df_fdc input-address-c1 input-name-form-user">
              <%= f.label "Endereço", for: "information-address" %>

              <%= f.text_field :street,
                placeholder: "Endereço",
                id: "information-address",
                class: "disable",
                disabled: true,
                value: adress_exists?(:street)
              %>
            </div>

            <div class="df df_fdc input-address-c2 input-name-form-user">
              <%= f.label "Número", for: "information-number" %>

              <%= f.text_field :number,
                placeholder: "Número",
                id: "information-number",
                class: "disable",
                disabled: true,
                value: adress_exists?(:number)
              %>
            </div>
          </div>

          <div class="df df_fdc complement w-input input-name-form-user">
              <%= f.label "Complemento", for: "address-complement" %>

              <%= f.text_field :complement,
                placeholder: "Complemento",
                id: "address-complement",
                class: "disable",
                disabled: true,
                value: adress_exists?(:complement)
              %>
          </div>

          <div class="button-edit-user buttons-desable w-input">
            <%= f.button "Alterar cadastro", type: "submit", class: "fw_light" %>
          </div>
        <% end %>
        <input type="button" value="Editar" id="habilit-inputs-edit">
      </section>
    </div>
  </div>
</main>